config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 3, maximum: 2000}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true,
             uniqueness: {case_sensitive: false},
             length: {minimum: 3, maximum: 20}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true,
             uniqueness: {case_sensitive: false},
             length: {maximum: 100},
             format: {with: VALID_EMAIL_REGEX}

  validates :password, presence: true,
             length: {minimum: 8, maximum: 20}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # calls the helper method set_article_params
  before_action :set_article_params, only: [:edit, :update, :show, :destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    # renders in application.html.erb
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:danger] = "Article was successfully deleted"
  end

  private

  def set_article_params
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:success] = "You have successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def index
    @users = User.paginate(page: params[:page], per_page: 6)

  end
  def new
    @user = User.new
  end
  def edit

  end
  def create
    @user = User.create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Alpha-Blog #{@user.username}!"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  def update
    if @user.update(user_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="well col-xs-8 col-xs-offset-2">
    <h4 class="cntr"><strong><%= link_to article.title, article_path(article) %></strong></h4>
    <hr class="divider">
    <h4 class="left"><%= truncate(article.description, length: 500) %></h4>
  <div class="article-actions">
    <%=  link_to "edit", edit_article_path(article), :class => "btn btn-primary btn-xs" %>
    <%=  link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger btn-xs" %>
    <small class="pull-right">
    <span>Created by:</span> <%= link_to article.user.username, user_path(article.user) %></br>
    <span>Posted:</span> <%= time_ago_in_words(article.created_at) %> ago</br>
    <span>Updated:</span> <%= time_ago_in_words(article.updated_at) %> ago
    </small>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :validate => true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-xs-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control title", placeholder: "Title", autofocus: "true" %>
          <% if (@article.errors.include?(:title)) %>
            <script type="text/javascript">
              function trigger(){
                $(".title").attr("placeholder", "<%= sanitize @article.errors[:title].first %>");
                $(".title").attr("value", null);
              };
              trigger();
            </script>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-xs-2">
          <%= f.label :description %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control description", placeholder: "Description" %><br/>
          <% if (@article.errors.include?(:description)) %>
            <script type="text/javascript">
              function trigger(){
                $(".description").attr("placeholder", "<%= sanitize @article.errors[:description].first %>");
                $(".description").html(null);
              };
              trigger();
            </script>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-success btn-sm submit" %>
          <button class="btn btn-info btn-sm"><%= link_to "Articles", articles_path %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="cntr">Edit this article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="cntr">Articles list:</h1>
<div class="cntr">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div class="cntr">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 class="cntr">This is where new articles are built</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="cntr"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">

  <div class="blog-info">
    <p><span>Created by:</span> <%= link_to @article.user.username, user_path(@article.user) %></p></br>
    <p><span>Posted:</span> <%= time_ago_in_words(@article.created_at) %> ago</p></br>
    <p><span>Updated:</span> <%= time_ago_in_words(@article.updated_at) %> ago</p>

  </div>
  <h4 class="cntr"><strong>Description:</strong></h4>
  <hr class="divider">
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), :class => "btn btn-info btn-xs" %>
    <%= link_to "Articles", articles_path, :class => "btn btn-success btn-xs" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger btn-xs pull-right" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <footer>
    <small>
      Copyright &copy; Created by <a href="https://github.com/adevenuto">Anthony DeVenuto</a>
    </small>
  </footer>
</div>

app/views/layouts/_header_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-Blog", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-buttons"><%= link_to "Home", root_path %></li>
        <li class="nav-buttons"><%= link_to "About", about_path %></li>
        <li class="dropdown nav-explore-button">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="nav-sub-explore-dropdown"><%= link_to "Articles", articles_path %></li>
            <% if logged_in? %>
              <li class="nav-sub-explore-dropdown"><%= link_to "Create Article", new_article_path %>
            <% end %>
            <li class="nav-sub-explore-dropdown"><%= link_to "Users", users_path %></li></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        <!-- navigation right -->
      <ul class="nav navbar-nav navbar-right">
        <!-- toggle logout button -->
        <% if !logged_in? %>
          <li class="nav-buttons"><%= link_to "Sign in", login_path %></li>
          <li class="nav-buttons"><%= link_to "Sign up", signup_path %></li>
        <% else %>
        <!-- setting dropdown menu -->
          <li class="nav-buttons logout"><%= link_to "Logout", logout_path, method: :delete, class: "logout-button" %></li>
          <li class="dropdown settings-button">
            <a href="#" class="dropdown-toggle glyphicon glyphicon-cog" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
            <ul class="dropdown-menu">
              <li class="nav-sub-explore-dropdown"><%= link_to "Edit your account", edit_user_path(current_user) %></li>
              <li class="nav-sub-explore-dropdown"><%= link_to "My Dashboard", user_path(current_user) %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<!-- displays success message from actions -->
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header_nav' %>
<%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/index.html.erb
<div class="jumbotron">
  <p class="jumbotron-inner"><span class="element typed-text"></span></p>
  <h1 id="jumbo-header">Alpha-Blog</h1></br></br>
  <p class="jumbotron-inner"><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<!-- insert body of homepage here -->


The standard Lorem Ipsum passage, used since the 1500s

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC

"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"

1914 translation by H. Rackham

"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"

Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC

"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."

1914 translation by H. Rackham

"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            Prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :validate => true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control username", placeholder: "Username", autofocus: "true" %>
          <% if (@user.errors.include?(:username)) %>
            <script type="text/javascript">
              function trigger(){
                $(".username").attr("placeholder", "<%= sanitize @user.errors[:username].first %>");
                $(".username").attr("value", null);
              };
              trigger();
            </script>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control email", placeholder: "Email" %><br/>
          <% if (@user.errors.include?(:email)) %>
            <script type="text/javascript">
              function trigger(){
                $(".email").attr("placeholder", "<%= sanitize @user.errors[:email].first %>");
                $(".email").attr("value", null);
              };
              trigger();
            </script>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %><br/>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control password", placeholder: "Password", autocomplete: "off" %><br/>
          <% if (@user.errors.include?(:password)) %>
            <script type="text/javascript">
            console.log("hello")
              function trigger(){
                $(".password").attr("placeholder", "<%= sanitize @user.errors[:password].first %>");
                $(".password").attr("value", null);
              };
              trigger();
            </script>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success btn-sm submit") %>
          <button class="btn btn-primary btn-sm"><%= link_to "Cancel", articles_path %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="cntr">Edit your account:</h1>

<%= render "form" %>

app/views/users/index.html.erb
<div class="user-info-container">
  <% @users.each do |user| %>
    <ul class="user-container">
      <li class="gravatar"><%= gravatar_for user %></li>
      <li><%= link_to user.username, user_path(user) %></li>
      <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
      <li><%= user.email %></li>
    </ul>
  <% end %>
  <div class="cntr">
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="cntr">Sign up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="cntr">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 cntr">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<div class="cntr">
  <%= will_paginate @user_articles %>
</div>
<h4 class="cntr">Checkout <%= @user.username %>'s articles</h4>
<%= render 'articles/article', obj: @user_articles %>